name: Deploy Astro y Django en Azure

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: |
          cd client
          npm install
      - name: Build Astro
        run: |
          cd client
          npm run build
      - name: Deploy Astro to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: "astro-frontend"
          slot-name: "production"
          package: "./client/dist"  
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}

    deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          cd server
          pip install -r requirements.txt

      - name: Apply Database Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd server
          python manage.py migrate

      - name: Deploy Django to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: "django-backend"
          slot-name: "production"
          package: "./server"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}


