# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - django-sustentability-backend

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python version
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'

            - name: Create and start virtual environment
              run: |
                  cd server
                  python -m venv venv
                  source venv/bin/activate

            - name: Install dependencies
              run: |
                  cd server
                  pip install -r requirements.txt

            - name: Zip artifact for deployment
              run: |
                  cd server
                  zip -r ../release.zip . -x "venv/*"

            - name: Upload artifact for deployment jobs
              uses: actions/upload-artifact@v4
              with:
                  name: python-app
                  path: release.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write #This is required for requesting the JWT

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: python-app

            - name: Unzip artifact for deployment
              run: unzip release.zip -d server

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.BACKEND_CLIENT_ID }}
                  tenant-id: ${{ secrets.BACKEND_TENANT_ID }}
                  subscription-id: ${{ secrets.BACKEND_SUB_ID }}

            - name: Install dependencies on Azure App Service
              run: |
                  cd server
                  python3 -m venv venv
                  source venv/bin/activate
                  pip install -r requirements.txt

            # Apply migrations (if necessary)
            - name: Apply migrations
              run: |
                  cd server
                  source venv/bin/activate
                  python manage.py migrate

            - name: 'Deploy to Azure Web App'
              uses: azure/webapps-deploy@v3
              id: deploy-to-webapp
              with:
                  app-name: 'django-sustentability-backend'
                  slot-name: 'Production'

            - name: Restart the app after deployment
              run: |
                  az webapp restart --name django-sustentability-backend --resource-group astro-blog-rg

